# Generated by Django 4.0.5 on 2022-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_bot_id', models.IntegerField()),
                ('link_id', models.IntegerField()),
                ('link_node1_id', models.IntegerField()),
                ('link_node2_id', models.IntegerField()),
                ('link_length', models.FloatField()),
                ('link_stiffness', models.FloatField()),
                ('link_dampening', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_bot_id', models.IntegerField()),
                ('node_id', models.IntegerField()),
                ('node_mass', models.FloatField()),
                ('node_position_x', models.FloatField()),
                ('node_position_y', models.FloatField()),
            ],
        ),
    ]
