# Generated by Django 4.0.5 on 2022-06-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softbots', '0002_bot_links_bot_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softbots.bot'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_node1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node1_id', to='softbots.node'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_node2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node2_id', to='softbots.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softbots.bot'),
        ),
    ]
